accounts/urls.py
from django.urls import path
from django.contrib.auth import logout
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('send_login_email', views.send_login_email, name='send-login-email'),
    path('login', views.login, name='login'),
    path('logout', logout, {'next_page': '/'}, name='logout')

]

lists/urls.py
from django.urls import path

from lists import views

app_name = 'lists'


urlpatterns = [
    path('new', views.new_list, name='new-list'),
    path('users/<email>/', views.my_lists, name='my-lists'),
    path('<int:list_id>/', views.view_list, name='view-list'),
]

superlists/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from lists import views
from lists import urls as list_urls
from accounts import urls as accounts_urls


urlpatterns = [
    path('', views.home_page, name='home'),
    path('lists/', include(list_urls)),
    path('accounts/', include(accounts_urls, namespace='accounts')),
    # path('admin/', admin.site.urls),
]

superlists2/superlists2/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    url(r'^$', 'lists.views.HomePageView', name='home'),
    url(r'^lists/the-only-list-in-the-world/$', 'lists.views.view_list', name='view_list'),
    url(r'^lists/new$', 'lists.views.new_list', name='new_list')
    # url(r'^blog/', include('blog.urls')),

    # url(r'^admin/', include(admin.site.urls)),
]

accounts/models.py
import uuid
from django.contrib import auth
from django.db import models

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=255)

lists/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse
from django.conf import settings


class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=CASCADE)

    @property
    def name(self):
        return self.item_set.first().text

    def get_absolute_url(self):
        return reverse('lists:view-list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=CASCADE)

lists/forms.py
from django import forms
from lists.models import Item, List
from django.core.exceptions import ValidationError


EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
            'placeholder': 'Enter a to-do item',
            'class': 'form-control input-lg',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class NewListForm(ItemForm):
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

accounts/views.py
import sys
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.contrib import messages
from accounts.models import Token
from django.urls import reverse
from django.contrib import auth


def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('accounts:login') + '?token=' + str(token.uid)
    )
    message_body = f'Use this link to log in:\n\n{url}'

    send_mail(
        'Your login link for Superlists',
        message_body,
        'noreply@superlists',
        [email]
    )
    messages.success(
        request,
        "Check your email, we've sent you a link ou can use to log in/"
    )
    return redirect('/')


def login(request):
    auth.authenticate(uid=request.GET.get('token'))
    auth.login('ack!')
    return redirect('/')

book_ex/lists/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def HomePageView(request):
    return render(request, 'home.html', {'new_item_text': request.POST.get('item_text', '')})

lists/views.py
from django.shortcuts import render, redirect
from lists.models import Item, List
from lists.forms import ItemForm, NewListForm, ExistingListItemForm
from django.contrib.auth import get_user_model
from django.urls import reverse


User = get_user_model()


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

superlists2/lists/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import Item


# Create your views here.
def HomePageView(request):
    return render(request, 'home.html')


def view_list(request):
    items = Item.objects.all()
    return render(request, 'list.html', {'items': items})


def new_list(request):
    Item.objects.create(request.POST['item_text'])
    # return redirect('/lists/the-only-list-in-the-world/')

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>To-Do lists</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylehseet">
        <link href="/static/base.css" rel="stylehseet">
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-default" role="navigation">
              <div class="container-fluid">
                <a class="navbar-brand" href="/">Superlists</a>
                {% if user.email %}
                    <ul class="nav navbar-nav navbar-left">
                    <li><a href="{% url 'lists:my-lists' user.email %}">My lists</a></li>
                    </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Logged in as {{ user.email }}</li>
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                  </ul>
                {% else %}
                  <form class="navbar-form navbar-right"
                        method="POST"
                        action="{% url 'accounts:send-login-email' %}">
                    <span>Enter email to log in:</span>
                    <input class="form-control" name="email" type="text" />
                    {% csrf_token %}
                  </form>
                {% endif %}
              </div>
            </nav>
            {% if messages %}
                <div class="row">
                  <div class="col-md-8">
                    {% for message in messages %}
                      {% if message.level_tag == 'success' %}
                        <div class="alert alert-success">{{ message }}</div>
                      {% else %}
                        <div class="alert alert-warning">{{ message }}</div>
                      {% endif %}
                    {% endfor %}
                  </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock %}</h1>
                        {% block list_form %}
                        <form method="POST" action="{% block form_action %}{% endblock %}">
                            {{ form.text }}
                            {% csrf_token %}
                            {% if form.errors %}
                            <div class="form-group has-error">
                                <span class="help-block"> {{ form.text.errors }}</span>
                            </div>
                        {% endif %}
                        </form>
                    {% endblock %}
                    </div>
                </div>
            </div>

        </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          {% block table %}
          {% endblock %}
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          {% block extra_content %}
          {% endblock %}
        </div>
      </div>
        <script src="/static/jquery-3.6.0.min.js"></script>
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %} {% url 'lists:new-list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %} Your To-Do list{% endblock %}

{% block form_action %}/lists/{{ list.id }} {% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

superlists2/lists/templates/home.html
<html>
<head>
    <meta charset="UTF-8">
    <title>To-Do lists</title>
</head>
<body>
    <h1>Your To-Do list</h1>

    <form method="POST">
        <input name="item_text" id="id_new_item" placeholder="Enter a to-do item"/>
        {% csrf_token %}
    </form>
    <table id="id_list_table">
        {% for item in items %}
           <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
</body>
</html>

superlists2/lists/templates/list.html
<html>
<head>
    <meta charset="UTF-8">
    <title>To-Do lists</title>
</head>
<body>
    <h1>Your To-Do list</h1>

    <form method="POST" action="/lists/new">
        <input name="item_text" id="id_new_item" placeholder="Enter a to-do item"/>
        {% csrf_token %}
    </form>
    <table id="id_list_table">
        {% for item in items %}
           <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
</body>
</html>